spring:
  h2:
    console:
      enabled: true
      path: /h2-consol
  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:h2:mem:testlog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true