spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:h2:mem:testlog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


testlog:
  secretKey: 6/XhJr9v+SVANc/Uj0H8I15S7JY8If0QqpEqFIFFeM8=
